service: dynamodb-serverless
frameworkVersion: '2'

provider:
  name: aws
  stage: dev
  region: us-west-2
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221

functions:
  hello:
    handler: handler.hello